package com.cuijixu.seckill.backend.entity;

import java.util.Date;

public class Pay_order {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.seckill_id
     *
     * @mbggenerated
     */
    private Long seckillId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.user_phone
     *
     * @mbggenerated
     */
    private Long userPhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.state
     *
     * @mbggenerated
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay_order.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.seckill_id
     *
     * @return the value of pay_order.seckill_id
     *
     * @mbggenerated
     */
    public Long getSeckillId() {
        return seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.seckill_id
     *
     * @param seckillId the value for pay_order.seckill_id
     *
     * @mbggenerated
     */
    public void setSeckillId(Long seckillId) {
        this.seckillId = seckillId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.user_phone
     *
     * @return the value of pay_order.user_phone
     *
     * @mbggenerated
     */
    public Long getUserPhone() {
        return userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.user_phone
     *
     * @param userPhone the value for pay_order.user_phone
     *
     * @mbggenerated
     */
    public void setUserPhone(Long userPhone) {
        this.userPhone = userPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.state
     *
     * @return the value of pay_order.state
     *
     * @mbggenerated
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.state
     *
     * @param state the value for pay_order.state
     *
     * @mbggenerated
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay_order.create_time
     *
     * @return the value of pay_order.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay_order.create_time
     *
     * @param createTime the value for pay_order.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
}